# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:camus_lints/camus.yaml

analyzer:
  # strong-mode:
  #   implicit-casts: false
  #   implicit-dynamic: false
  # Try enabling this experiment by adding it to the command line when compiling and running
  # enable-experiment:
  #   - extension-methods
  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # treat missing returns as a warning (not a hint)
    missing_return: warning
    todo: ignore
    public_member_api_docs: ignore
