name: camus_iconfont
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  test: ^1.16.0
  camus_lints: ^1.1.0
dependencies:
  args: ^2.3.1
