name: camus_iconfont
description: generate your font files & Flutter Icons
version: 1.0.0
repository: https://github.com/camus-design/camus_iconfont.git

environment:
  sdk: '>=2.16.1 <3.0.0'


dev_dependencies:
  lints: ^2.0.1
  test: ^1.16.0
dependencies:
  args: ^2.3.1
  code_builder: ^4.1.0
  dart_style: ^2.2.3
  path: ^1.8.0
  recase: ^4.1.0

executables:
  camus_iconfont: camus_iconfont
